language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint pythonflow
  - py.test --cov --cov-fail-under=100 --cov-report=term-missing
